apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pv9wl6DUUKjWD62og7wsp5XDKbVZSUSiCeokueFQj5Y=,iv:weYj5cnnIcN8HmCGB2R+PfEqXsuuWxtGathElKEU53Q=,tag:azjrIGBNKfQCwHl3jXsfPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHJMcXpIZmVEOEZLam4v
        RVl5U2lGcW1uY2hVNkFtR1krZ1l1dTNWTEZVCkcrcDFFaUhESlkrSnRLU05OK091
        R29rM0FLNGtCbHZIUEhmaHBXUzF5RmcKLS0tIHdIUVh5Qmx6VFhxeUNIdU5TdWJF
        RkR6QXhjVVlVMllZSEJTYnd2YzZVNW8K9Q0efvJbcAQ21svxsoDA08q0ElmOtOrw
        V2ZY8v7hTw7mqhE9t4HJNURxPwI75bThn4HsQsKy+6CprR9JbAv+xQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T16:01:28Z"
  mac: ENC[AES256_GCM,data:4tu7tOiOUcgylrWHc5qLVC4s3HLsN0gFN/mevtTElt5isQw0hxDzIsUQp62/d2hGL3lCmNp1Nz41RpoXWHGphoNEmGWDDy88uTWQoQzrPemaQwrhmyzVxQvLKIvTRa/8zYU/cGvpkkQzUXAIoFyK39PrGdoyQpI+E/ar0dGwT7g=,iv:lU2OX8iA9HXfym1SkS5dCtc5HjC+Pvl9wA298BfOudk=,tag:3eWa1mU/J9ikFXqlxXn87Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: github-notification-token
stringData:
  token: ENC[AES256_GCM,data:pMCa6VDaw83zCEL0jnomp5G3lkdr1Mj06+TiXBhDNTcuwVHWTpAGaVZiXJv9wruO27dp703NKSQnwIB2B7/tUpNjUb8L6ib4+ZtSzUFwaLZDEZig0Wr+0BHsvdOI,iv:X0QFK/O7avd1A2qDpF6f3jXCMxiZXTuClrZWSFy5W4o=,tag:iHwfk5qXMw1SKE40yVsLBQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHJMcXpIZmVEOEZLam4v
        RVl5U2lGcW1uY2hVNkFtR1krZ1l1dTNWTEZVCkcrcDFFaUhESlkrSnRLU05OK091
        R29rM0FLNGtCbHZIUEhmaHBXUzF5RmcKLS0tIHdIUVh5Qmx6VFhxeUNIdU5TdWJF
        RkR6QXhjVVlVMllZSEJTYnd2YzZVNW8K9Q0efvJbcAQ21svxsoDA08q0ElmOtOrw
        V2ZY8v7hTw7mqhE9t4HJNURxPwI75bThn4HsQsKy+6CprR9JbAv+xQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T16:01:28Z"
  mac: ENC[AES256_GCM,data:4tu7tOiOUcgylrWHc5qLVC4s3HLsN0gFN/mevtTElt5isQw0hxDzIsUQp62/d2hGL3lCmNp1Nz41RpoXWHGphoNEmGWDDy88uTWQoQzrPemaQwrhmyzVxQvLKIvTRa/8zYU/cGvpkkQzUXAIoFyK39PrGdoyQpI+E/ar0dGwT7g=,iv:lU2OX8iA9HXfym1SkS5dCtc5HjC+Pvl9wA298BfOudk=,tag:3eWa1mU/J9ikFXqlxXn87Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
