apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:yEj69iv/YFkddtv3K8ptceLgAVJRPJ2vMPrHNqwl8TscoHTa6RreF4nnJQbrzYl8M/9rBMAGjg0KYT5oGHLFwlzQKXoydT60YNpNwSNGB1HSuBYkfHcifGazArSnnzi0B/HAPfotA+wYrWy0AEcMV55wSoaCyRMRGEptKH/e9ClyCgDvpZfk6MOjwTZ+6FgleoVDjOAITWnFLWALAXDNCedmQb/amyIbms3YsAR+f7hsgo5panySqFnfbqJ2bZZLHRwa+5wchA60YOEg7eMfs4GJvdgycewGyJPXisgTQOZHS94xGaSyXx/Sn3vzWiOXWS+xOtfzPOrQFEry2oEOdXcg5Ovg9mtOaMt+6uGmVhQaU5FNAe+LnGCsp8pZiHPoC3fZ0nFQtF7J3wiHLFw8tul9S4U9TtRbLFgIM8Zcl3Sh7VuogKM01REjmTBJfkFkk2R+EWiKZ3v4SjImbIfpAV5LBQgl0WZm3GWlA2D2JLJ6O4dk7nfAgNQPXbGNuvqYAnS2NypJvmcfLC12RkyGjMkGTfOx227K6I0QdpShT4vML2LI+rAXJ3ODVTp8eZ/RyYqyFST1WOWtJwodd/d6wdeZeKHP/VlVdd+raG8qE0QzOIC5kXvknD7C24Bp85ukWmXGVot4+cIrbvYCyD4x2Dsd9HVlZJxPBEHO+a82Z31eLDaw6PTXlnilsjIPCW+2lvl+feF+K1JPCxAQZvncdV6jD4PyNNUmekSIMZ+7pMISz3uYaWnd6u4/VnOqaAKYTIR8rbuUVXj7J+7AFRXgxabt3o5He93WqJHWVWDrF3dOJFQ1OuTNCiYrxoy/ov4AKKanG1Zf70cR3oUMgf/czUux,iv:BqsDM0ZSQkOYK9Ur7o0wiKvH/cQGwbLJY3O/9e2R4nM=,tag:d7XxDDHLAMDuO1iuSbtmGg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T14:23:43Z"
  mac: ENC[AES256_GCM,data:4XyG3VBO/xbwfLnEoTs82vVQwovjsuCDQyE4ynZAoy5ADyf9jbrSkCtJJPd04xohQ2haAK3asVBwDsF1Iq/GNdnL2akXufB/7BaUemK02HmOGPOUCFUpvm/QcmCj0EF5j9x9JUqwdJLNC9wxJ9sd6b7BXcB4659RT2OejkKw4ws=,iv:7rFPLsj3gUW0uQERNTderfjerzuv1PnAFokK134bhVg=,tag:wGjOaYVf2z+TGi/jqwC+dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials
type: Opaque
data:
  1password-credentials.json: ENC[AES256_GCM,data:SBWWK4Sz6UtmbeElpH0eREty2aoU/DA8SFJdwWqzv2DFAlLBZFrn5lrprEZHJvPOnGi5mdsETCphv8pHoTQs73wIPuxHL+8ehdhO5k7QuF+wblAG+SQllt5GNlU+6dAVwYyE93KDXF7+bJWA2Ea2zMEv3Z0QoR7nnCmBQFJtatiAUQg1dTOxreCaUyCTDx4xYfaQi0Y3zxCMZdST/sQgxINk+bDujGBQiFfSP3vX4qMtblLhjQLnjbXULAoNjpqA3hr+bnMkamJjOPlbS/RWDT+sOLT0z3ODOS6BTNbLSWO6V0I1jsaIUxATuO6Q4gkeBjytG0LW+QHgOVi2Chw75YMh3VuQeanNIH1/JMbk0yUDr7Yv4IC3g4NxOD6riv1/lVFcZNUQuqyD2u/0cr8BdPABBiRuhVZPH3lLQtT8jouc4si18swTVUOJ6cbFDuZK/OO+chVl3AYK0tuYevaBO55SXzI4Ltil3E4sT54jTeqqRPpPGY6H7XPM7zk82Y2sO7COWCaHFh3AQy2pLdWwcsyuKnvXAkKxZxxmQFCVgeGKrmaA1QSenm1uwjhadncTfSC1HndDgrrUOXP/50UBk3WLpJzd1q6pPPwx7ilbfXuH0EnSbj8IjQINHnSvp/vxqin1gTe6WSW8P2aTfl/TJ++RfV1ZjigFnTVSQ4xp+S1IWKgWpNG4zsUE7bxO7H7vcwei/E6khXlqGqVPcPXdpQcBzehRk3EILW1vS6iDJALp3rjvZ9XvTp86drXnLScT1vaK1qcXP+1NDYPFhim4EZo1ZxRh0ZYgdczLZoz5jXf1mQRLAxkoUenB894/D7WjSlV26QUyNj6Z0XaKT7f6JAclh9S5v6fqo+fLJOO4thRmh5tn7LMc9uw+v1nekLPAwADN2kePSf0TryrdCpDamwocXr4ZmZa6QEffyRYknEs4kxfQWW9uHzls6dqXidC2sHlm155lWmGotwnwYKDnaM0sRZuu8uqe08I2dklmMCu0VZmOUY6a5qlKOHiRJJVhhd8dH/LDnJQPJ+mwtLKyMKbDMxs6uj9/guApDuyK2ORPdAe1lPjRc3tcjdfeOi+85tgDrbmSXtgFJX46QmnGq9p254Nt7Q9Y29ge5s1ut25vb0Kk81KqNr5IfjgBrgqfCrsNv2v4FForR8/SqTpZYI9aYoOxXtSaPRyPS6MvTprP3GEdTjPQLldUUTfiG7n7XlRfserQPg0pGUjLtiP9uVoKvRK2mY3d2qbj/B3Q/nO1TZX9DlizwNWP0Wspe0TAJeL1Wm+7nVGiM8uJvceAQWlWFcQ6BIrOjH9cLJ9FxXHirZ62h8ydPvECAsYepCTzoOMGMQy819410J8bb8Di0PxSnRC+5fgshJsOtCdGX5Qlsi2kMhFCWdDITStt89ALWP4MuTPgrlhiUBaQiC7C3OkiQ7M7H8kzcJLvAB4HJ/+2kC6BA0H5ISP2eNL/gICBM+VTMTx2GzSj8CgPw97Nb6FHN5TG2cqFfxqkVm+rhu7ue6kUIYF0ZFsbbGIL0IS7IMa/zwRYjLMEIu90O7Js9IhvMzJdwgbLkl9v2TKNatTQoRPhNNpRbcx2hyZmjYtwemoDAoO6ZbimwjZk0ugws/YqUsJs/JhThmB+WwshyA9QcVrXH/+V3HQ1FC1VykOOESTO05p4zwE83cIgNFFafD2/3tJYXDujVIubrsVxHca492f8F80O0PmW1RqwtH+kOgccFtf+wfbZ8MWfrBN8ZyH0MnsonAfi7BVzXaXh0OE4XwXy+gaQ3VKx/v2obJZGkiPQ30Vw53+daQyI7HfRilxZP9IseJzgW3xS3qtcFgNjwKZpThKw3WlDyzihH5WPT/TXTYzWKt0T73qkgvPbTKrHROOWA5+ov3XymHBonlxsYI8Lga2IbvVBiW3aSrB9vcN+QaisKg/H/3lI,iv:oMK9TlSgEFguo4y931kocwuPOvFyqxDo5oKKZoeHcYg=,tag:WgJxX8BwHS/jqj1twBdxCg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T14:23:43Z"
  mac: ENC[AES256_GCM,data:4XyG3VBO/xbwfLnEoTs82vVQwovjsuCDQyE4ynZAoy5ADyf9jbrSkCtJJPd04xohQ2haAK3asVBwDsF1Iq/GNdnL2akXufB/7BaUemK02HmOGPOUCFUpvm/QcmCj0EF5j9x9JUqwdJLNC9wxJ9sd6b7BXcB4659RT2OejkKw4ws=,iv:7rFPLsj3gUW0uQERNTderfjerzuv1PnAFokK134bhVg=,tag:wGjOaYVf2z+TGi/jqwC+dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
