---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secret.yaml
  - ./shared.yaml
  - ./immich-secrets.yaml
  - ./immich.yaml
  - ./n8n-secrets.yaml
  - ./n8n.yaml
