---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-canary
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        ready
        forward . /etc/resolv.conf
        cache 30
    }
